version: '2'
services:
    ednagateway-cassandra:
        container_name: ednagateway-cassandra
        image: cassandra:2.2.5
        # volumes:
        #     - ~/volumes/jhipster/ednagateway/cassandra/:/var/lib/cassandra/data
        ports:
            - 7000:7000
            - 7001:7001
            - 7199:7199
            - 9042:9042
            - 9160:9160
    ednagateway-cassandra-migration:
        extends:
            file: cassandra-migration.yml
            service: ednagateway-cassandra-migration
        links:
            - ednagateway-cassandra
        environment:
            - CREATE_KEYSPACE_SCRIPT=create-keyspace.cql
