version: '2'
services:
    ednaapi-app:
        image: localhost:5000/ednaapi
        external_links:
            - ednaapi-postgresql:postgresql
            - jhipster-registry:registry
        environment:
            - SPRING_PROFILES_ACTIVE=prod
            - SPRING_CLOUD_CONFIG_URI=http://admin:admin@registry:8761/config
            - SPRING_DATASOURCE_URL=jdbc:postgresql://postgresql:5432/ednaapi
            - JHIPSTER_SLEEP=10
            - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://admin:admin@registry:8761/eureka
    ednaapi-postgresql:
        container_name: ednaapi-postgresql
        image: postgres:9.5.2
        environment:
            - POSTGRES_USER=ednaapi
            - POSTGRES_PASSWORD=
    
    ednagateway-app:
        image: localhost:5000/ednagateway
        external_links:
            - ednagateway-postgresql:postgresql
            - jhipster-registry:registry
        environment:
            - SPRING_PROFILES_ACTIVE=prod
            - SPRING_CLOUD_CONFIG_URI=http://admin:admin@registry:8761/config
            - SPRING_DATASOURCE_URL=jdbc:postgresql://postgresql:5432/ednagateway
            - SPRING_DATA_CASSANDRA_CONTACTPOINTS=cassandra
            - JHIPSTER_SLEEP=30
            - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://admin:admin@registry:8761/eureka
        ports:
            - 8080:8080
    ednagateway-postgresql:
        container_name: ednagateway-postgresql
        image: postgres:9.5.2
        environment:
            - POSTGRES_USER=ednagateway
            - POSTGRES_PASSWORD=
    
    uaa-app:
        image: localhost:5000/uaa
        external_links:
            - uaa-postgresql:postgresql
            - jhipster-registry:registry
        environment:
            - SPRING_PROFILES_ACTIVE=prod
            - SPRING_CLOUD_CONFIG_URI=http://admin:admin@registry:8761/config
            - SPRING_DATASOURCE_URL=jdbc:postgresql://postgresql:5432/uaa
            - JHIPSTER_SLEEP=10
            - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://admin:admin@registry:8761/eureka
    uaa-postgresql:
        container_name: uaa-postgresql
        image: postgres:9.5.2
        environment:
            - POSTGRES_USER=uaa
            - POSTGRES_PASSWORD=
    
    jhipster-registry:
        extends:
            file: jhipster-registry.yml
            service: jhipster-registry
    jhipster-elasticsearch:
        extends:
            file: jhipster-console.yml
            service: jhipster-elasticsearch
    jhipster-logstash:
        extends:
          file: jhipster-console.yml
          service: jhipster-logstash
    jhipster-console:
        extends:
            file: jhipster-console.yml
            service: jhipster-console
    jhipster-mail:
        extends:
            file: mail-server.yml
            service: mail
volumes:
    maildata:
        driver: local
